version: '2'
services:
    simplejavatest-app:
        image: simplejavatest
        external_links:
            - simplejavatest-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/SimpleJavaTest
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    simplejavatest-postgresql:
        extends:
            file: postgresql.yml
            service: simplejavatest-postgresql
